version: '3'

services:

  database:
    image: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "hello_world_ci_dev"
    restart: always
    volumes:
      - ./docker/data/postgres:/var/lib/postgres/data
  web:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - .:/app
      ports:
        - "4000:4000"
      depends_on:
        - database