version: '3'

services:

  database:
    image: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "hello_world_test"
    restart: always
    volumes:
      - ./docker/data/postgres:/var/lib/postgres/data
  test:
      build:
        context: .
        dockerfile: test.Dockerfile
      volumes:
          - ./test_result:/app/test_result
      depends_on:
        - database